spring:
  application:
    name:backend
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    # mysql 기본 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}/s10p21s003_dev?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}

server:
  port: 8081
  servlet:
    context-path: /api

#쿼리문 로그
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
